# Generated by Django 3.0.5 on 2020-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='order',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
