# Generated by Django 3.0.5 on 2020-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_auto_20200503_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
