# Generated by Django 3.0.5 on 2021-03-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_auto_20200510_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
