# Generated by Django 4.2 on 2024-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_auto_20210313_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
